name:                pipes-zlib-decoder
version:             1.0.0
github:              "ellej/pipes-zlib-decoder"
license:             BSD3
author:              "Jelle Lingier"
maintainer:          "jelle.lingier@gmail.com"
copyright:           "2019 Jelle Lingier"

extra-source-files:
- README.adoc

# Metadata used when publishing your package
synopsis: Pipe that decodes a zlib stream.
category: Codec, Pipes

description: Please see the README on GitHub at <https://github.com/ellej/pipes-zlib-decoder#readme>

dependencies:
- base >= 4.7 && < 5
- pipes >=4.1
- containers >=0.5
- mtl >=2.1

default-extensions:
- Rank2Types
- LambdaCase
- TupleSections
- FlexibleContexts

library:
  source-dirs: src

tests:
  stack-test-test:
    main: Main.hs
    source-dirs: testsuite
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipes-zlib-decoder
    - zlib >=0.5.4
    - bytestring >=0.10
    - transformers >=0.3
    - tasty >=0.7
    - tasty-hunit >=0.4
    - tasty-quickcheck >=0.3
